# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: Main Catmem

concurrency:
  group: azure-catmem
  cancel-in-progress: true

on:
  push:
    branches:
      - bugfix-*
      - enhancement-*
      - feature-*
      - workaround-*
      - dev
      - unstable
      - master

env:
  GITHUB_REPOSITORY: $GITHUB_REPOSITORY

jobs:

  #=====================================================================================================================
  # Setup
  #=====================================================================================================================

  # Node 0
  setup-demikernel0:
    name: Node 0
    uses: demikernel/demikernel/.github/workflows/setup.yml@dev
    secrets:
      host: ${{ secrets.CATMEM_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}


  #=====================================================================================================================
  # Setup Completed
  #=====================================================================================================================

  setup:
    name: Setup Completed
    needs: [setup-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Setup Completed!"

  #=====================================================================================================================
  # Build
  #=====================================================================================================================

  # Node 0
  build-demikernel0:
    name: Node 0
    needs: [setup]
    uses: demikernel/demikernel/.github/workflows/build.yml@dev
    with:
      libos: catmem
    secrets:
      host: ${{ secrets.CATMEM_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}


  #=====================================================================================================================
  # Build Completed
  #=====================================================================================================================

  # Node 0
  build:
    name: Build Completed
    needs: [build-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Build Completed!"

  #=====================================================================================================================
  # Compile Test
  #=====================================================================================================================

  compile-demikernel0:
    name: Node 0 / Compile
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Build Release
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CATMEM_HOSTNAME_A }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORTNUM }}
        envs: GITHUB_REPOSITORY
        script: |
          echo repository: $GITHUB_REPOSITORY
          cd $GITHUB_REPOSITORY
          make all DEBUG=no LIBOS=catmem


  #=====================================================================================================================
  # Compile Test Completed
  #=====================================================================================================================

  # Node 0
  compile:
    name: Compile Completed
    needs: [compile-demikernel0]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Compile Completed!"

  #=====================================================================================================================
  # Unit Test
  #=====================================================================================================================

  # Unit Test
  test-unit:
    name: Unit Test
    needs: [compile]
    uses: demikernel/demikernel/.github/workflows/test-nowait.yml@dev
    with:
      targetA: "test-unit LIBOS=catmem"
      targetB: "test-unit LIBOS=catmem"
    secrets:
      hostA: ${{ secrets.CATMEM_HOSTNAME_A }}
      hostB: ${{ secrets.CATMEM_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #=====================================================================================================================
  # Unit Test Completed
  #=====================================================================================================================

  # Node 0
  test-unit-completed:
    name: Unit Test Completed
    needs: [test-unit]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Unit Test Completed!"

  #=====================================================================================================================
  # Test Pipe Push Pop
  #=====================================================================================================================

  # Test Pipe Push Pop
  test-pipe-push-pop:
    name: Pipe Push Pop
    needs: [test-unit-completed]
    uses: demikernel/demikernel/.github/workflows/test.yml@dev
    with:
      targetA: "test-system-rust LIBOS=catmem TEST=pipe-push-pop ARGS='--server test-pipe-push-pop'"
      targetB: "test-system-rust LIBOS=catmem TEST=pipe-push-pop ARGS='--client test-pipe-push-pop'"
    secrets:
      hostA: ${{ secrets.CATMEM_HOSTNAME_A }}
      hostB: ${{ secrets.CATMEM_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #=====================================================================================================================
  # Test Pipe Completed
  #=====================================================================================================================

  # Node 0
  test-pipe-push-pop-completed:
    name: Test Pipe Completed
    needs: [test-pipe-push-pop]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Test Pipe Completed!"

  #=====================================================================================================================
  # Test Pipe Ping Pong
  #=====================================================================================================================

  # Test Pipe Ping Pong
  test-pipe-ping-pong:
    name: Pipe Ping Pong
    needs: [test-pipe-push-pop-completed]
    uses: demikernel/demikernel/.github/workflows/test.yml@dev
    with:
      targetA: "test-system-rust LIBOS=catmem TEST=pipe-ping-pong ARGS='--server test-pipe-ping-pong'"
      targetB: "test-system-rust LIBOS=catmem TEST=pipe-ping-pong ARGS='--client test-pipe-ping-pong'"
    secrets:
      hostA: ${{ secrets.CATMEM_HOSTNAME_A }}
      hostB: ${{ secrets.CATMEM_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}

  #=====================================================================================================================
  # Test Pipe Ping Pong Completed
  #=====================================================================================================================

  # Node 0
  test-pipe-ping-pong-completed:
    name: Test Pipe Completed
    needs: [test-pipe-ping-pong]
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: echo "Test Pipe Completed!"

  #=====================================================================================================================
  # Cleanup
  #=====================================================================================================================

  # Node 0
  cleanup-demikernel0:
    name: Node 0
    if: always()
    needs: [test-pipe-ping-pong-completed]
    uses: demikernel/demikernel/.github/workflows/cleanup.yml@dev
    secrets:
      host: ${{ secrets.CATMEM_HOSTNAME_A }}
      port: ${{ secrets.PORTNUM }}
      key: ${{ secrets.SSHKEY }}
      username: ${{ secrets.USERNAME }}
