# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: SSH Setup

on:
  workflow_call:
    secrets:
      hostname:
        required: false
      port:
        required: true
      key:
        required: true
      username:
        required: true

jobs:

  setup-ssh:
    name: SSH Setup
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p $HOME/.ssh/
        echo "${{ secrets.key }}" > "$HOME/.ssh/id_rsa"
        chmod 400 $HOME/.ssh/id_rsa
        echo "Host *" > $HOME/.ssh/config
        echo -e "\tStrictHostKeyChecking no" >> $HOME/.ssh/config
        echo -e "\tIdentityFile $HOME/.ssh/id_rsa" >> $HOME/.ssh/config
        echo -e "\tIdentitiesOnly yes" >> $HOME/.ssh/config
        echo -e "\tPasswordAuthentication no" >> $HOME/.ssh/config
        echo -e "\tUser ${{ secrets.username }}" >> $HOME/.ssh/config
        echo -e "\tPort ${{ secrets.port }}" >> $HOME/.ssh/config
